spring:
  application:
    name: training-service
  cache:
    type: redis
  data:
    redis:
      host: redis-training-db
      port: 6379
      timeout: 2s
  config:
    import: optional:configserver:http://config-server:8888
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
